# Advanced P.A.R.T.H Configuration
# All parameters configurable - NO HARDCODING

# Backend Selection
backend: ollama  # Options: "ollama", "huggingface"

# Generation Parameters
params:
  temperature: 0.2
  top_p: 0.9
  max_tokens: 1024
  seed: 7

# Model Configuration
models:
  ollama: "qwen2.5:1.5b"
  huggingface: "microsoft/phi-4"
  embedding: "sentence-transformers/all-MiniLM-L6-v2"

# File Paths
prompts:
  system: ./prompts/system.txt
  tools: ./prompts/tools.md

# Database Configuration
database:
  provider: postgresql  # Future: support sqlite, mysql
  connection:
    dbname: parthdb
    user: parth_user
    password: parth123
    host: localhost
    port: 5432
    timeout: 30

# Memory/Embedding Configuration
memory:
  session_id: default
  embedding_dim: 384
  similarity_threshold: 1.5  # Increased from 0.7 to include more results
  max_history_retrieval: 10
  enable_similarity_search: true

# Ollama Configuration
ollama:
  host: "http://127.0.0.1:11434"
  timeout: 600
  stream: true

# Hugging Face Configuration
huggingface:
  dtype: "auto"
  device: "auto"
  trust_remote_code: false
  cache_dir: "./hf_cache"
  torch_dtype: "float16"

# Performance Settings
performance:
  enable_garbage_collection: true
  memory_limit_mb: 4096
  batch_size: 1
  parallel_processing: false

# Logging Configuration
logging:
  level: WARNING  # Only show warnings and errors, suppress INFO and DEBUG
  file: ./logs/parth.log
  max_file_size_mb: 10
  backup_count: 3

# Vision Configuration
vision:
  enabled: true
  model_type: "yolo11n"  # Options: yolov8n, yolov8s, mobilenet
  model_path: "./yolov8n.pt"
  real_time: true
  logging:
    suppress_ultralytics: true  # Suppress YOLO batch progress bars
    suppress_model_loading: true  # Suppress model loading output
    suppress_inference: true  # Suppress inference progress bars
    show_fps: false  # Show FPS counter in terminal
    log_level: "ERROR"  # Logging level for vision system
  camera:
    source: 0  # Webcam source (0 for default camera)
    width: 640
    height: 480
    fps: 30
  detection:
    confidence_threshold: 0.5
    max_detections: 10
  performance:
    frame_skip: 1  # Process every nth frame for better performance
    resize_input: true
    use_gpu: false  # Set to true if GPU available

# Security Settings
security:
  max_input_length: 4096
  rate_limit_per_minute: 60
  sanitize_input: true
